# Generated by Django 6.0.1 on 2026-01-18 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('FAST', 'FAST'), ('CARDIAC', 'Cardiac'), ('LUNG', 'Lung'), ('AORTA', 'Aorta'), ('IVC', 'IVC'), ('OTHER', 'Other')], max_length=20)),
                ('indication', models.CharField(blank=True, max_length=200)),
                ('finding', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('INDETERMINATE', 'Indeterminate')], max_length=20)),
                ('confidence', models.IntegerField(blank=True, help_text='Confidence 1–5', null=True)),
                ('supervisor_present', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
