# Generated by Django 6.0.1 on 2026-01-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: confidence 1–5', null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='exam_type',
            field=models.CharField(choices=[('FAST', 'FAST'), ('CARDIAC', 'Cardiac'), ('LUNG', 'Lung'), ('AORTA', 'Aorta'), ('IVC', 'IVC'), ('MSK', 'MSK'), ('OB', 'Obstetrics'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
