# Generated by Django 6.0.1 on 2026-01-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_scan_confidence_alter_scan_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Optional: name of supervising staff/resident', max_length=100),
        ),
    ]
