# Generated by Django 6.0.1 on 2026-01-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_casequestion_casestep_clinicalcase_casechoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz_slug',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuizBestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.PositiveIntegerField()),
                ('quiz_title', models.CharField(blank=True, max_length=200)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_best_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quiz_id'],
                'unique_together': {('user', 'quiz_id')},
            },
        ),
    ]
