# Generated by Django 6.0.1 on 2026-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='exam_type',
            field=models.CharField(choices=[('RUQ', 'RUQ Abdomen'), ('LUQ', 'LUQ Abdomen'), ('AORTA', 'Aorta'), ('SUBXIPHOID', 'Subxiphoid (Cardiac)'), ('PLAX', 'Parasternal Long Axis (Cardiac)'), ('PSAX', 'Parasternal Short Axis (Cardiac)'), ('IVC', 'IVC'), ('OB_FIRST', 'First-Trimester (Obstetrics)')], max_length=20),
        ),
    ]
