# Generated by Django 6.0.1 on 2026-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_scan_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='iq_anatomy_landmarks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Poor demonstration, 2=Excellent demonstration', null=True, verbose_name='Scanning Skill: Anatomy/Landmarks'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_comments',
            field=models.TextField(blank=True, help_text='Optional comments on image quality', verbose_name='IQ Scale Comments'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_completeness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Inadequate views, 2=Ideal views', null=True, verbose_name='Interpretability: Completeness'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_depth',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Inadequate for visualization, 2=Ideal', null=True, verbose_name='Technical Skill: Depth'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_gain_presets',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Inadequate for visualization, 2=Ideal', null=True, verbose_name='Technical Skill: Gain/Presets'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_labelling',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Inadequate labeling, 2=Ideal labelling', null=True, verbose_name='Interpretability: Labelling'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_probe_choice',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Inadequate for visualization, 2=Ideal', null=True, verbose_name='Technical Skill: Probe Choice'),
        ),
        migrations.AddField(
            model_name='scan',
            name='iq_probe_control',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Inadequate'), (1, '1 - Adequate'), (2, '2 - Ideal/Excellent')], help_text='0=Poor probe control, 2=Excellent probe control', null=True, verbose_name='Scanning Skill: Probe Control'),
        ),
    ]
