# Generated by Django 6.0.1 on 2026-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_scan_iq_anatomy_landmarks_scan_iq_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_context',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Half Day'), ('SELF', 'Self Logged')], default='SELF', help_text='Where was this scan performed?', max_length=10, verbose_name='Scan Context'),
        ),
    ]
