# Generated by Django 6.0.1 on 2026-03-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_add_scan_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.PositiveIntegerField(db_index=True)),
                ('key', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_heading', models.CharField(blank=True, help_text="Optional section heading shown before this question (e.g. 'Ultrasound Physics Questions')", max_length=200)),
                ('question_text', models.TextField()),
                ('choice_a', models.CharField(blank=True, max_length=500)),
                ('choice_b', models.CharField(blank=True, max_length=500)),
                ('choice_c', models.CharField(blank=True, max_length=500)),
                ('choice_d', models.CharField(blank=True, max_length=500)),
                ('choice_e', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.CharField(help_text='A, B, C, D, or E', max_length=1)),
                ('image_url', models.URLField(blank=True, help_text='Optional POCUS image URL displayed above this question')),
                ('label', models.CharField(blank=True, help_text='Short topic label used in analytics', max_length=200)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['quiz_id', 'order'],
                'unique_together': {('quiz_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='QuizShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.PositiveIntegerField(db_index=True)),
                ('key', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('sample_answer', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for auto-scoring')),
                ('min_keywords', models.PositiveIntegerField(default=2)),
                ('image_url', models.URLField(blank=True, help_text='Optional POCUS image URL displayed with this question')),
            ],
            options={
                'verbose_name': 'Quiz Short Answer',
                'verbose_name_plural': 'Quiz Short Answers',
                'ordering': ['quiz_id', 'order'],
                'unique_together': {('quiz_id', 'key')},
            },
        ),
    ]
