# Generated by Django 6.0.1 on 2026-03-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_quizquestion_quizshortanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='POCUSProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Protocol name shown on the tab (e.g. 'FAST Scan')", max_length=100)),
                ('tab_id', models.SlugField(help_text="URL-safe tab ID, no spaces (e.g. 'fast', 'lung', 'cardiac')", unique=True)),
                ('icon_class', models.CharField(blank=True, default='fas fa-circle', help_text="Font Awesome icon class (e.g. 'fas fa-search', 'fas fa-lungs', 'fas fa-heart')", max_length=60)),
                ('description', models.TextField(blank=True, help_text='Short subtitle shown below the protocol heading')),
                ('content', models.TextField(blank=True, help_text='Full protocol body as HTML — paste your HTML here, it will be rendered directly on the page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tab order — lower numbers appear first (leftmost)')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this protocol from learners')),
            ],
            options={
                'verbose_name': 'POCUS Protocol',
                'verbose_name_plural': 'POCUS Protocols',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('pdf', 'PDF / Document'), ('guideline', 'Guideline'), ('link', 'External Link')], default='link', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Link to the resource (article, video, PDF, etc.)')),
                ('image_url', models.URLField(blank=True, help_text='Optional thumbnail image URL to display on the card')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower numbers appear first')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from learners')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='key',
            field=models.CharField(help_text='Unique identifier within the quiz (e.g. q1, q2, q3). New questions should continue the sequence — if the quiz has q1-q5, use q6.', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display position in the quiz. 1 = shown first. New questions should use the next available number (e.g. if quiz has 5 questions, enter 6).'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz_id',
            field=models.PositiveIntegerField(db_index=True, help_text='Which quiz this question belongs to: 1 = E-FAST + CVC Basics, 2 = POCUS Session #1, 3 = Focused Echo'),
        ),
        migrations.AlterField(
            model_name='quizshortanswer',
            name='key',
            field=models.CharField(help_text='Unique identifier within the quiz (e.g. sa1, sa2, sa3). New questions should continue the sequence.', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizshortanswer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display position in the quiz. 1 = shown first. New questions should use the next available number.'),
        ),
        migrations.AlterField(
            model_name='quizshortanswer',
            name='quiz_id',
            field=models.PositiveIntegerField(db_index=True, help_text='Which quiz this question belongs to: 1 = E-FAST + CVC Basics, 2 = POCUS Session #1, 3 = Focused Echo'),
        ),
    ]
