# Generated by Django 6.0.1 on 2026-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_seed_pocus_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestep',
            name='media_url',
            field=models.URLField(blank=True, help_text='Optional YouTube embed URL or direct video/image URL to display above the question'),
        ),
    ]
