from django.db import migrations

# Quiz 4: Ocular POCUS — Anatomy & Biosafety (CSV questions 11–20)
QUIZ_4_QUESTIONS = [
    {
        "key": "q1", "order": 1,
        "label": "Ocular probe selection and depth",
        "question_text": "Which ultrasound transducer is recommended for ocular POCUS, and what depth setting is appropriate for posterior chamber assessment?",
        "choice_a": "Phased array probe; depth 10–12 cm",
        "choice_b": "Low-frequency curvilinear probe; depth 8 cm",
        "choice_c": "High-frequency linear transducer; depth approximately 4 cm",
        "choice_d": "Endocavitary probe; depth 6 cm",
        "correct_answer": "C",
        "explanation": "A high-frequency linear transducer is used for ocular ultrasound. Depth is set to approximately 4 cm for full posterior chamber views, and can be reduced further when focusing on the anterior chamber and pupil.",
        "image_url": "",
    },
    {
        "key": "q2", "order": 2,
        "label": "Globe pressure safety",
        "question_text": "When performing ocular ultrasound, why is anchoring the hand or arm critically important?",
        "choice_a": "To improve Doppler signal acquisition",
        "choice_b": "To prevent excessive pressure on the globe, which could cause injury or worsen pathology",
        "choice_c": "To stabilize the probe for Doppler color flow imaging",
        "choice_d": "To allow the patient to keep their eye open during scanning",
        "correct_answer": "B",
        "explanation": "Anchoring the hand or arm — on the patient's shoulder, cheek, or forehead — prevents unintended pressure on the globe. Pressure on an injured or ruptured globe can exacerbate injury and should be strictly avoided.",
        "image_url": "",
    },
    {
        "key": "q3", "order": 3,
        "label": "Anterior chamber thermal risk",
        "question_text": "Why is the anterior chamber of the eye particularly susceptible to ultrasound-induced thermal injury compared to other body structures?",
        "choice_a": "The anterior chamber contains highly vascular tissue that amplifies heat production",
        "choice_b": "The cornea and lens are avascular and cannot dissipate heat through vasodilation; additionally, the lens has a high acoustic absorption coefficient",
        "choice_c": "The aqueous humor has a very low specific heat capacity",
        "choice_d": "The iris absorbs mechanical energy and converts it entirely to heat",
        "correct_answer": "B",
        "explanation": "The cornea and lens are avascular — unlike skin, they cannot dilate vessels to dissipate heat. The lens also has a high acoustic absorption coefficient, meaning it absorbs significant ultrasound energy and converts it to heat, making thermal injury a real risk with improper settings.",
        "image_url": "",
    },
    {
        "key": "q4", "order": 4,
        "label": "Safe TI and MI thresholds",
        "question_text": "What are the recommended tissue index (TI) and mechanical index (MI) thresholds for safe ocular ultrasound?",
        "choice_a": "TI < 2, MI < 1.0",
        "choice_b": "TI < 1, MI < 0.23",
        "choice_c": "TI < 0.5, MI < 0.1",
        "choice_d": "TI < 3, MI < 0.5",
        "correct_answer": "B",
        "explanation": "For safe ocular ultrasound: TI must be < 1 and MI must be < 0.23. Using a musculoskeletal preset instead of an ocular preset can result in an MI of 0.5 — more than twice the safe threshold — highlighting the importance of using the correct machine setting.",
        "image_url": "",
    },
    {
        "key": "q5", "order": 5,
        "label": "MSK preset safety concern",
        "question_text": "A colleague suggests using the musculoskeletal (MSK) setting for ocular ultrasound. What is the concern?",
        "choice_a": "The MSK setting uses too low a frequency to visualize the anterior chamber",
        "choice_b": "The MSK setting results in a mechanical index of approximately 0.5, exceeding the safe ocular threshold of 0.23",
        "choice_c": "The MSK setting disables Doppler, which is required for pupillary assessment",
        "choice_d": "The MSK setting depth is fixed at 10 cm and cannot be adjusted",
        "correct_answer": "B",
        "explanation": "The MSK preset has a mechanical index of approximately 0.5 — more than double the safe ocular limit of 0.23. An ocular preset brings the MI down to approximately 0.2. Most machines allow a custom ocular preset to be created if one is not available.",
        "image_url": "",
    },
    {
        "key": "q6", "order": 6,
        "label": "Eye movement purpose during scan",
        "question_text": "When scanning the eye with ultrasound, the patient is asked to look left, right, up, and down. What is the primary purpose of this maneuver?",
        "choice_a": "To assess extraocular muscle integrity",
        "choice_b": "To allow complete visualization of the entire vitreous chamber",
        "choice_c": "To test consensual pupillary response",
        "choice_d": "To reposition a dislocated lens for better imaging",
        "correct_answer": "B",
        "explanation": "Having the patient move their eyes in all directions allows complete sweeping visualization of the vitreous chamber, which is important for detecting pathology such as retinal detachment, vitreous hemorrhage, or foreign bodies that might otherwise be missed with static imaging.",
        "image_url": "",
    },
    {
        "key": "q7", "order": 7,
        "label": "Optic nerve sonographic appearance",
        "question_text": "What is the sonographic appearance and location of the optic nerve on ocular ultrasound?",
        "choice_a": "A hyperechoic bright band at the anterior margin of the globe",
        "choice_b": "A hypoechoic structure visible in the far field posterior to the vitreous chamber",
        "choice_c": "A pulsatile structure located just anterior to the iris",
        "choice_d": "A thin echogenic ring surrounding the entire globe",
        "correct_answer": "B",
        "explanation": "The optic nerve appears as a hypoechoic (dark) area in the far field, posterior to the vitreous humor on ocular ultrasound. It is the landmark used for optic nerve sheath diameter measurement and for identifying whether a retinal detachment is attached to it.",
        "image_url": "",
    },
    {
        "key": "q8", "order": 8,
        "label": "Indications for ocular POCUS",
        "question_text": "Which of the following correctly identifies an indication for ocular POCUS?",
        "choice_a": "Routine screening for glaucoma in asymptomatic patients",
        "choice_b": "Suspected increased intracranial pressure in a patient with severe headache and blurred vision",
        "choice_c": "Monitoring intraocular pressure during systemic hypertension management",
        "choice_d": "Assessment of colour vision deficits",
        "correct_answer": "B",
        "explanation": "Ocular POCUS has several indications: vision problems, eye trauma with limited visualization, anything that cannot be assessed with an ophthalmoscope, and suspected elevated ICP. Measuring optic nerve sheath diameter is an established use for screening for elevated ICP, such as in IIH.",
        "image_url": "",
    },
    {
        "key": "q9", "order": 9,
        "label": "Gain management technique",
        "question_text": "How should gain be managed during an ocular ultrasound examination?",
        "choice_a": "Start with maximum gain to ensure no pathology is missed, then reduce gradually",
        "choice_b": "Use a fixed standardized gain throughout the exam regardless of findings",
        "choice_c": "Start with lower gain to detect bright pathology first (e.g. retinal detachment), then increase gain to detect subtler findings (e.g. vitreous detachment/hemorrhage)",
        "choice_d": "Gain should not be adjusted — only focal zone positioning should be changed",
        "correct_answer": "C",
        "explanation": "Start with lower gain — this is sufficient to detect bright findings like retinal detachment while reducing artifact. Then increase gain to detect subtler, less echogenic pathology such as vitreous detachment or early vitreous hemorrhage. Comparing with the normal contralateral eye helps calibrate for artifact.",
        "image_url": "",
    },
    {
        "key": "q10", "order": 10,
        "label": "Pupillary response assessment technique",
        "question_text": "A patient presents with complete inability to open their eye after facial trauma. You want to assess for pupillary response. Which ultrasound technique allows this?",
        "choice_a": "Scanning through the closed lid with the probe oriented axially from above",
        "choice_b": "Approaching laterally or inferiorly with generous gel and scanning with the lids closed to directly visualize iris and pupil constriction",
        "choice_c": "Using Doppler mode to detect pulsatile flow within the iris",
        "choice_d": "This cannot be assessed with ultrasound — direct visualization is mandatory",
        "correct_answer": "B",
        "explanation": "By placing the probe lateral or inferior to the closed eye with a generous gel cushion, you can directly visualize the iris and pupil. Applying light to the closed lid (directly and consensually) will produce visible pupillary constriction on ultrasound — useful when the eye cannot be opened.",
        "image_url": "",
    },
]

# Quiz 5: Ocular Emergencies (CSV questions 1–10)
QUIZ_5_QUESTIONS = [
    {
        "key": "q1", "order": 1,
        "label": "Retinal detachment appearance",
        "question_text": "A retinal detachment on ultrasound is characteristically described as which of the following?",
        "choice_a": "A thin, unattached membrane that moves like a washing machine",
        "choice_b": "A V-shaped hyperechoic filament attached to the optic nerve",
        "choice_c": "A cobweb-like lacy appearance throughout the vitreous",
        "choice_d": "An hourglass-shaped bilateral structure in the posterior chamber",
        "correct_answer": "B",
        "explanation": "Retinal detachment appears as a V-shaped hyperechoic filament in the posterior chamber. Critically, it remains attached to the optic nerve — this is the key distinguishing feature from vitreous detachment.",
        "image_url": "",
    },
    {
        "key": "q2", "order": 2,
        "label": "Retinal vs vitreous detachment",
        "question_text": "When differentiating retinal detachment from vitreous detachment on ultrasound, which statement is most accurate?",
        "choice_a": "Vitreous detachment is attached to the optic nerve; retinal detachment is not",
        "choice_b": "Retinal detachment requires high gain to visualize; vitreous detachment does not",
        "choice_c": "Vitreous detachment is NOT attached to the optic nerve and appears as a thinner, less echogenic membrane",
        "choice_d": "Both appear identical and cannot be differentiated by ultrasound",
        "correct_answer": "C",
        "explanation": "Unlike retinal detachment, vitreous detachment is NOT attached to the optic nerve. It also appears as a thinner, less echo-dense structure. Higher gain settings may be needed to visualize it.",
        "image_url": "",
    },
    {
        "key": "q3", "order": 3,
        "label": "MAC off — macula involvement",
        "question_text": "What does 'MAC off' mean in the context of retinal detachment, and why is it clinically urgent?",
        "choice_a": "The macula is intact, so central vision is preserved",
        "choice_b": "The retina is detached laterally but the macula is spared",
        "choice_c": "The macula is involved in the detachment, resulting in loss of central vision requiring early treatment",
        "choice_d": "The optic nerve is not involved, making the prognosis favourable",
        "correct_answer": "C",
        "explanation": "MAC off means the macula is involved in the detachment. This causes complete loss of central vision. If not treated quickly (usually within days), permanent vision loss results even with successful repair.",
        "image_url": "",
    },
    {
        "key": "q4", "order": 4,
        "label": "Vitreous hemorrhage in diabetics",
        "question_text": "A 55-year-old diabetic presents with decreased vision described as 'like a waterfall.' Ultrasound shows diffuse echogenic material in the posterior chamber without a clear membrane. What is the most likely diagnosis?",
        "choice_a": "Retinal detachment",
        "choice_b": "Vitreous detachment",
        "choice_c": "Vitreous hemorrhage",
        "choice_d": "Choroidal detachment",
        "correct_answer": "C",
        "explanation": "Vitreous hemorrhage classically presents in diabetics due to proliferative vascular disease. It appears as diffuse, lacy/cobweb-like or clump-like material filling the vitreous — no clear membrane, unlike retinal or vitreous detachment.",
        "image_url": "",
    },
    {
        "key": "q5", "order": 5,
        "label": "Combined retinal + choroidal detachment",
        "question_text": "A patient with blunt eye trauma is on warfarin. Ultrasound shows a V-shaped structure attached to the optic nerve AND a separate convex structure posteriorly that is attached anteriorly and posteriorly but not in the middle. What is the combined finding?",
        "choice_a": "Retinal detachment + vitreous hemorrhage",
        "choice_b": "Retinal detachment + choroidal detachment",
        "choice_c": "Lens dislocation + vitreous detachment",
        "choice_d": "Globe rupture + hyphema",
        "correct_answer": "B",
        "explanation": "The V-shaped structure attached to the optic nerve = retinal detachment. The convex structure with anterior and posterior attachment but free in the middle = choroidal detachment (from hemorrhage within the choroid). Common in trauma, especially with anticoagulation.",
        "image_url": "",
    },
    {
        "key": "q6", "order": 6,
        "label": "ONSD for elevated ICP",
        "question_text": "You are assessing a 20-year-old obese female with headache and blurred vision. What measurement and threshold suggests elevated intracranial pressure on ocular ultrasound?",
        "choice_a": "Optic disc elevation > 2 mm",
        "choice_b": "Optic nerve sheath diameter > 5 mm, measured 3 mm behind the globe",
        "choice_c": "Anterior chamber depth < 2.5 mm",
        "choice_d": "Vitreous chamber diameter > 25 mm",
        "correct_answer": "B",
        "explanation": "The optic nerve sheath diameter is measured 3 mm posterior to the globe. A diameter > 5 mm in adults is associated with elevated intracranial pressure. This is the technique used to screen for IIH or in mass casualty triage.",
        "image_url": "",
    },
    {
        "key": "q7", "order": 7,
        "label": "Hyphema management",
        "question_text": "A hyphema that has been allowed to consolidate by keeping the patient supine becomes clinically important because:",
        "choice_a": "It causes corneal scarring from direct pressure",
        "choice_b": "Consolidated clotted hyphema is very difficult to treat and is associated with poor visual outcomes",
        "choice_c": "It indicates a ruptured globe requiring emergent surgery",
        "choice_d": "It leads to vitreous detachment in most cases",
        "correct_answer": "B",
        "explanation": "A hyphema that consolidates from lying flat becomes clotted and adherent to the anterior chamber. This is extremely difficult to treat and usually results in poor vision. Key take-home: always keep hyphema patients upright.",
        "image_url": "",
    },
    {
        "key": "q8", "order": 8,
        "label": "Vitreous detachment features",
        "question_text": "On ocular POCUS a vitreous detachment can be distinguished from retinal detachment by which of the following features?",
        "choice_a": "Vitreous detachment is more echo-bright and requires lower gain",
        "choice_b": "Vitreous detachment shows a 'washing machine' effect with eye movement and is NOT attached to the optic nerve",
        "choice_c": "Retinal detachment oscillates more with eye movement",
        "choice_d": "Both require identical gain settings to visualize",
        "correct_answer": "B",
        "explanation": "Vitreous detachment shows a characteristic 'washing machine' appearance when the patient looks side to side. It is not attached to the optic nerve, requires higher gain to visualize, and is less echogenic than retinal detachment.",
        "image_url": "",
    },
    {
        "key": "q9", "order": 9,
        "label": "Ocular foreign body — gold standard",
        "question_text": "Which of the following is the gold standard for evaluation of ocular foreign body, and what is the role of ultrasound?",
        "choice_a": "MRI is gold standard; ultrasound is contraindicated",
        "choice_b": "CT is gold standard; ultrasound can rule-in but evidence is limited",
        "choice_c": "Ultrasound is gold standard; CT is adjunct",
        "choice_d": "Plain X-ray is gold standard; ultrasound is not useful",
        "correct_answer": "B",
        "explanation": "CT remains the gold standard for ocular foreign body. Ultrasound can detect certain foreign bodies (metallic objects show ring-down artifact) and can rule-in, but the evidence is limited. Also: if globe rupture is suspected, avoid pressure on the globe with the probe.",
        "image_url": "",
    },
    {
        "key": "q10", "order": 10,
        "label": "Lens dislocation mechanism",
        "question_text": "In lens dislocation seen on ocular ultrasound, which of the following correctly describes the mechanism and appearance?",
        "choice_a": "The ciliary muscle hypertrophies, pushing the lens anteriorly into the anterior chamber",
        "choice_b": "The lens separates from the ciliary body and falls posteriorly into the vitreous chamber",
        "choice_c": "The lens remains in place but becomes opacified — diagnosed by loss of its normal echogenicity",
        "choice_d": "The lens fuses with the iris, causing pupillary block",
        "correct_answer": "B",
        "explanation": "In lens dislocation, the ciliary body lets go and the lens falls back into the vitreous/posterior chamber. On ultrasound, you see the iris without a lens behind it, and the lens is visualized displaced elsewhere in the globe. Most often traumatic.",
        "image_url": "",
    },
]


def seed(apps, schema_editor):
    QuizQuestion = apps.get_model("logbook", "QuizQuestion")
    for q in QUIZ_4_QUESTIONS:
        if not QuizQuestion.objects.filter(quiz_id=4, key=q["key"]).exists():
            QuizQuestion.objects.create(quiz_id=4, **q)
    for q in QUIZ_5_QUESTIONS:
        if not QuizQuestion.objects.filter(quiz_id=5, key=q["key"]).exists():
            QuizQuestion.objects.create(quiz_id=5, **q)


def unseed(apps, schema_editor):
    QuizQuestion = apps.get_model("logbook", "QuizQuestion")
    QuizQuestion.objects.filter(quiz_id__in=[4, 5]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0015_quizquestion_explanation"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
