from django.db import migrations

QUESTIONS = [
    # General
    {
        "key": "q1", "order": 1, "section_heading": "",
        "label": "Primary goal of first trimester POCUS",
        "question_text": "What is the primary goal of first trimester POCUS?",
        "choice_a": "Diagnose ectopic pregnancy",
        "choice_b": "Assess fetal viability",
        "choice_c": "Identify intrauterine pregnancy",
        "choice_d": "Measure fetal heart rate",
        "correct_answer": "C",
        "explanation": "The main goal is to confirm IUP — not to rule in ectopic or assess viability. Confirming IUP significantly reduces the likelihood of a clinically significant ectopic pregnancy.",
        "image_url": "",
    },
    {
        "key": "q2", "order": 2, "section_heading": "",
        "label": "Heterotopic pregnancy risk",
        "question_text": "Which patient population has a higher risk of heterotopic pregnancy?",
        "choice_a": "Multiparous women",
        "choice_b": "Women with prior miscarriage",
        "choice_c": "Patients undergoing fertility treatment",
        "choice_d": "Teenagers",
        "correct_answer": "C",
        "explanation": "Fertility treatments (e.g. IVF) significantly increase the risk of heterotopic pregnancy — a simultaneous intrauterine and extrauterine pregnancy. The general population risk is ~1:30,000; with IVF it rises to ~1:100.",
        "image_url": "",
    },
    # Technique
    {
        "key": "q3", "order": 3, "section_heading": "Technique",
        "label": "Scanning sequence",
        "question_text": "What is the correct scanning sequence?",
        "choice_a": "Transverse then longitudinal",
        "choice_b": "Longitudinal then transverse",
        "choice_c": "Oblique only",
        "choice_d": "Coronal only",
        "correct_answer": "B",
        "explanation": "Begin with the longitudinal (sagittal) view to orient the uterus and identify the endometrial stripe, then sweep transversely. This sequence ensures systematic coverage of the uterine cavity.",
        "image_url": "",
    },
    {
        "key": "q4", "order": 4, "section_heading": "",
        "label": "Free fluid assessment timing",
        "question_text": "When should you assess for free fluid?",
        "choice_a": "Always",
        "choice_b": "Only in stable patients",
        "choice_c": "When ruptured ectopic suspected",
        "choice_d": "Only after confirming IUP",
        "correct_answer": "C",
        "explanation": "Free fluid assessment is most relevant when a ruptured ectopic is suspected. Free fluid in the pelvis or Morrison's pouch in the correct clinical context suggests hemorrhage from a ruptured ectopic.",
        "image_url": "",
    },
    # Confirming IUP
    {
        "key": "q5", "order": 5, "section_heading": "Confirming IUP (5 Criteria)",
        "label": "First step confirming IUP",
        "question_text": "What is the FIRST step in confirming an IUP?",
        "choice_a": "Identify fetal pole",
        "choice_b": "Measure CRL",
        "choice_c": "Identify bladder and uterus",
        "choice_d": "Assess adnexa",
        "correct_answer": "C",
        "explanation": "The first step is orienting yourself — identify the bladder (landmark) and uterus before looking for the gestational sac. Without proper orientation, it is easy to misidentify structures.",
        "image_url": "",
    },
    {
        "key": "q6", "order": 6, "section_heading": "",
        "label": "Gestational sac location",
        "question_text": "Where must the gestational sac be located?",
        "choice_a": "Cervix",
        "choice_b": "Myometrium",
        "choice_c": "Endometrium",
        "choice_d": "Adnexa",
        "correct_answer": "C",
        "explanation": "A true IUP gestational sac must be located within the endometrial cavity. A sac in the myometrium, cervix, or adnexa suggests an abnormal implantation site.",
        "image_url": "",
    },
    {
        "key": "q7", "order": 7, "section_heading": "",
        "label": "What confirms IUP",
        "question_text": "Which of the following confirms an IUP?",
        "choice_a": "Free fluid",
        "choice_b": "Gestational sac alone",
        "choice_c": "Yolk sac or fetal pole in uterus",
        "choice_d": "β-hCG >3000",
        "correct_answer": "C",
        "explanation": "A gestational sac alone does NOT confirm IUP — it could be a pseudogestational sac. The presence of a yolk sac or fetal pole within an intrauterine sac is required to confirm IUP.",
        "image_url": "",
    },
    {
        "key": "q8", "order": 8, "section_heading": "",
        "label": "Myometrial mantle thickness",
        "question_text": "What is the required myometrial mantle thickness?",
        "choice_a": ">3 mm",
        "choice_b": ">5 mm",
        "choice_c": ">7–10 mm",
        "choice_d": ">15 mm",
        "correct_answer": "C",
        "explanation": "The myometrial mantle surrounding the gestational sac should be >7–10 mm to exclude interstitial (cornual) ectopic pregnancy. A thin mantle raises concern for abnormal implantation.",
        "image_url": "",
    },
    {
        "key": "q9", "order": 9, "section_heading": "",
        "label": "NDIUP declaration",
        "question_text": "If any IUP criteria are absent, what should you declare?",
        "choice_a": "Normal pregnancy",
        "choice_b": "Ectopic pregnancy",
        "choice_c": "NDIUP",
        "choice_d": "Miscarriage",
        "correct_answer": "C",
        "explanation": "NDIUP (No Definite Intrauterine Pregnancy) is declared when the criteria for IUP confirmation are not met. This is not a diagnosis of ectopic — it is a finding that requires clinical correlation and follow-up.",
        "image_url": "",
    },
    {
        "key": "q10", "order": 10, "section_heading": "",
        "label": "Heterotopic risk factor",
        "question_text": "Which factor must be absent to confidently declare IUP?",
        "choice_a": "Pain",
        "choice_b": "Bleeding",
        "choice_c": "Risk factors for heterotopic pregnancy",
        "choice_d": "High β-hCG",
        "correct_answer": "C",
        "explanation": "In patients with risk factors for heterotopic pregnancy (especially IVF), an IUP does NOT exclude a simultaneous ectopic pregnancy. Risk factors for heterotopic must be absent before IUP confirmation is considered reassuring.",
        "image_url": "",
    },
    # Gestational Sac & Early Findings
    {
        "key": "q11", "order": 11, "section_heading": "Gestational Sac & Early Findings",
        "label": "Earliest GS visibility (TA)",
        "question_text": "Earliest gestational sac visibility (transabdominal)?",
        "choice_a": "3 weeks",
        "choice_b": "4 weeks",
        "choice_c": "5–6 weeks",
        "choice_d": "8 weeks",
        "correct_answer": "C",
        "explanation": "The gestational sac is typically first visible on transabdominal ultrasound at 5–6 weeks gestation. Earlier visualization requires transvaginal ultrasound (possible from ~4.5 weeks).",
        "image_url": "",
    },
    {
        "key": "q12", "order": 12, "section_heading": "",
        "label": "Discriminatory β-hCG (TA)",
        "question_text": "Discriminatory β-hCG level for transabdominal ultrasound?",
        "choice_a": "1000 IU/L",
        "choice_b": "2000 IU/L",
        "choice_c": "3000 IU/L",
        "choice_d": "5000 IU/L",
        "correct_answer": "C",
        "explanation": "The discriminatory β-hCG level for transabdominal ultrasound is ~3000 IU/L. At this level, an IUP should be visible. For transvaginal ultrasound, the threshold is lower (~1500–2000 IU/L).",
        "image_url": "",
    },
    {
        "key": "q13", "order": 13, "section_heading": "",
        "label": "FEEDS criteria",
        "question_text": "Which of the following is part of the FEEDS criteria for a true gestational sac?",
        "choice_a": "Flat shape",
        "choice_b": "Central location",
        "choice_c": "Eccentric location",
        "choice_d": "Anechoic rim",
        "correct_answer": "C",
        "explanation": "FEEDS: Fundal or eccentric location, Echogenic rim (double decidual sign), Early appearance, Double ring, Size >5 mm. Eccentric location distinguishes a true gestational sac from a pseudogestational sac (which is central).",
        "image_url": "",
    },
    {
        "key": "q14", "order": 14, "section_heading": "",
        "label": "Minimum GS size in FEEDS",
        "question_text": "Minimum size of gestational sac in FEEDS criteria?",
        "choice_a": ">2 mm",
        "choice_b": ">3 mm",
        "choice_c": ">5 mm",
        "choice_d": ">10 mm",
        "correct_answer": "C",
        "explanation": "The FEEDS criteria specify that the gestational sac should be >5 mm to be reliably characterized. Smaller sacs may be indeterminate.",
        "image_url": "",
    },
    # Pseudogestational Sac
    {
        "key": "q15", "order": 15, "section_heading": "Pseudogestational Sac",
        "label": "Pseudogestational sac feature",
        "question_text": "Which feature suggests a pseudogestational sac rather than a true gestational sac?",
        "choice_a": "Double decidual sign",
        "choice_b": "Eccentric location",
        "choice_c": "Central location",
        "choice_d": "Yolk sac present",
        "correct_answer": "C",
        "explanation": "A pseudogestational sac lies centrally within the endometrial cavity (between the endometrial layers), whereas a true gestational sac implants eccentrically within the endometrium. The presence of a yolk sac always confirms a true gestational sac.",
        "image_url": "",
    },
    {
        "key": "q16", "order": 16, "section_heading": "",
        "label": "True gestational sac appearance",
        "question_text": "A true gestational sac typically has:",
        "choice_a": "A single echogenic rim",
        "choice_b": "Double hyperechoic rings (double decidual sign)",
        "choice_c": "No vascularity",
        "choice_d": "An irregular shape",
        "correct_answer": "B",
        "explanation": "A true gestational sac demonstrates the double decidual sign — two concentric hyperechoic rings surrounding the anechoic sac. This represents the decidua capsularis and decidua parietalis.",
        "image_url": "",
    },
    {
        "key": "q17", "order": 17, "section_heading": "",
        "label": "Pseudogestational sac size",
        "question_text": "Pseudogestational sacs are usually:",
        "choice_a": ">10 mm",
        "choice_b": "<5 mm",
        "choice_c": "Highly vascular",
        "choice_d": "Contain a fetal pole",
        "correct_answer": "B",
        "explanation": "Pseudogestational sacs associated with ectopic pregnancy are usually small (<5 mm), centrally located, without a double decidual sign, and never contain a yolk sac or fetal pole.",
        "image_url": "",
    },
    # Development Timeline
    {
        "key": "q18", "order": 18, "section_heading": "Development Timeline",
        "label": "Yolk sac appearance timing",
        "question_text": "The yolk sac first appears at approximately:",
        "choice_a": "4 weeks",
        "choice_b": "5 weeks",
        "choice_c": "6 weeks",
        "choice_d": "7 weeks",
        "correct_answer": "B",
        "explanation": "The yolk sac is visible by approximately 5 weeks on transvaginal ultrasound. It is the first definitive sign of an IUP and appears before the fetal pole.",
        "image_url": "",
    },
    {
        "key": "q19", "order": 19, "section_heading": "",
        "label": "Fetal pole appearance timing",
        "question_text": "The fetal pole first appears at approximately:",
        "choice_a": "4 weeks",
        "choice_b": "5 weeks",
        "choice_c": "6 weeks",
        "choice_d": "8 weeks",
        "correct_answer": "C",
        "explanation": "The fetal pole is typically visible by 6 weeks gestation on transvaginal ultrasound. Cardiac activity should be detectable soon after the fetal pole is identified.",
        "image_url": "",
    },
    {
        "key": "q20", "order": 20, "section_heading": "",
        "label": "CRL for cardiac activity",
        "question_text": "Cardiac activity should be seen when CRL (crown-rump length) is:",
        "choice_a": "2–3 mm",
        "choice_b": "4–7 mm",
        "choice_c": "8–10 mm",
        "choice_d": ">10 mm",
        "correct_answer": "B",
        "explanation": "Cardiac activity should be detectable by transvaginal ultrasound when the CRL reaches 4–7 mm. Absence of cardiac activity at this size is concerning for embryonic demise.",
        "image_url": "",
    },
    {
        "key": "q21", "order": 21, "section_heading": "",
        "label": "FHR <100 significance",
        "question_text": "A fetal heart rate (FHR) of <100 bpm in the first trimester indicates:",
        "choice_a": "Normal finding",
        "choice_b": "Ectopic pregnancy",
        "choice_c": "Poor prognosis",
        "choice_d": "Measurement error",
        "correct_answer": "C",
        "explanation": "A FHR <100 bpm in the first trimester is associated with a significantly increased risk of miscarriage. Normal first trimester FHR is typically 110–170 bpm. Bradycardia (<100 bpm) is a poor prognostic sign.",
        "image_url": "",
    },
    # NDIUP
    {
        "key": "q22", "order": 22, "section_heading": "NDIUP (No Definite IUP)",
        "label": "NDIUP differential",
        "question_text": "NDIUP (No Definite Intrauterine Pregnancy) includes all of the following EXCEPT:",
        "choice_a": "Early IUP",
        "choice_b": "Ectopic pregnancy",
        "choice_c": "Normal confirmed IUP",
        "choice_d": "Miscarriage",
        "correct_answer": "C",
        "explanation": "NDIUP is a category that encompasses early IUP (too early to visualize), ectopic pregnancy, and miscarriage (complete or incomplete). A normal confirmed IUP by definition is NOT an NDIUP.",
        "image_url": "",
    },
    {
        "key": "q23", "order": 23, "section_heading": "",
        "label": "Empty uterus + β-hCG >3000",
        "question_text": "Empty uterus on transabdominal ultrasound with β-hCG >3000 IU/L suggests:",
        "choice_a": "Normal early pregnancy",
        "choice_b": "Likely ectopic pregnancy",
        "choice_c": "Blighted ovum",
        "choice_d": "Molar pregnancy",
        "correct_answer": "B",
        "explanation": "At β-hCG >3000 IU/L (discriminatory zone for TA ultrasound), an IUP should be visible. An empty uterus above this threshold is highly suspicious for ectopic pregnancy or a complete miscarriage.",
        "image_url": "",
    },
    # Ectopic Pregnancy
    {
        "key": "q24", "order": 24, "section_heading": "Ectopic Pregnancy",
        "label": "Most specific ectopic sign",
        "question_text": "The most specific ultrasound sign of an ectopic pregnancy is:",
        "choice_a": "Free fluid in pelvis",
        "choice_b": "Empty uterus",
        "choice_c": "Extrauterine gestational sac containing a yolk sac or fetal pole",
        "choice_d": "Pain on probe palpation",
        "correct_answer": "C",
        "explanation": "Visualizing an extrauterine gestational sac with a yolk sac or fetal pole is the most specific (definitive) sign of ectopic pregnancy. Empty uterus and free fluid are sensitive but non-specific signs.",
        "image_url": "",
    },
    {
        "key": "q25", "order": 25, "section_heading": "",
        "label": "Tubal ring sign",
        "question_text": "The 'tubal ring sign' on ultrasound represents:",
        "choice_a": "Corpus luteum",
        "choice_b": "Endometrium",
        "choice_c": "Trophoblastic tissue surrounding an ectopic gestational sac",
        "choice_d": "Hemorrhage in the fallopian tube",
        "correct_answer": "C",
        "explanation": "The tubal ring sign is a hyperechoic ring seen in the adnexa, representing trophoblastic tissue surrounding the ectopic gestational sac within the fallopian tube. It must be distinguished from the corpus luteum (which is ovarian).",
        "image_url": "",
    },
    {
        "key": "q26", "order": 26, "section_heading": "",
        "label": "Free fluid to Morrison's pouch",
        "question_text": "Free fluid extending to Morrison's pouch (hepatorenal space) suggests:",
        "choice_a": "Benign finding",
        "choice_b": "Normal pregnancy",
        "choice_c": "Possible ruptured ectopic with significant intraperitoneal hemorrhage",
        "choice_d": "UTI",
        "correct_answer": "C",
        "explanation": "Free fluid in Morrison's pouch in the context of a possible ectopic pregnancy indicates significant intraperitoneal hemorrhage and is an emergency finding suggesting rupture. This patient requires immediate surgical consultation.",
        "image_url": "",
    },
    {
        "key": "q27", "order": 27, "section_heading": "",
        "label": "Empty uterus + free fluid",
        "question_text": "In a patient with a positive pregnancy test, empty uterus on POCUS + free fluid in the pelvis → next step?",
        "choice_a": "Discharge with outpatient follow-up",
        "choice_b": "Repeat scan in 1 week",
        "choice_c": "Assume ectopic pregnancy until proven otherwise — immediate OB/GYN consultation",
        "choice_d": "Ignore and re-check β-hCG",
        "correct_answer": "C",
        "explanation": "An empty uterus with free fluid in a pregnant patient is an ectopic pregnancy until proven otherwise. This combination warrants immediate OB/GYN consultation and should not be dismissed or deferred.",
        "image_url": "",
    },
    # Subchorionic Hemorrhage
    {
        "key": "q28", "order": 28, "section_heading": "Subchorionic Hemorrhage",
        "label": "Most common 1st trimester bleeding cause",
        "question_text": "The most common cause of first trimester vaginal bleeding seen on ultrasound is:",
        "choice_a": "Ectopic pregnancy",
        "choice_b": "Molar pregnancy",
        "choice_c": "Subchorionic hemorrhage",
        "choice_d": "Placenta previa",
        "correct_answer": "C",
        "explanation": "Subchorionic hemorrhage (bleeding between the chorion and uterine wall) is the most common ultrasound finding in first trimester vaginal bleeding. It appears as a crescent-shaped hypoechoic or mixed echogenicity collection adjacent to the gestational sac.",
        "image_url": "",
    },
    {
        "key": "q29", "order": 29, "section_heading": "",
        "label": "Large subchorionic hemorrhage outcome",
        "question_text": "A larger subchorionic hemorrhage is associated with:",
        "choice_a": "Better pregnancy outcomes",
        "choice_b": "Increased risk of miscarriage",
        "choice_c": "No effect on outcome",
        "choice_d": "Ectopic pregnancy",
        "correct_answer": "B",
        "explanation": "Larger subchorionic hemorrhages (particularly those >25% of gestational sac volume) are associated with increased risk of miscarriage and adverse outcomes. Size and location relative to the sac are important prognostic factors.",
        "image_url": "",
    },
    # Pregnancy Failure
    {
        "key": "q30", "order": 30, "section_heading": "Pregnancy Failure",
        "label": "Diagnostic of pregnancy failure",
        "question_text": "Which finding is diagnostic of pregnancy failure?",
        "choice_a": "Gestational sac 15 mm with no embryo",
        "choice_b": "Gestational sac >25 mm with no embryo",
        "choice_c": "Gestational sac 10 mm with no yolk sac",
        "choice_d": "CRL 5 mm with no heartbeat",
        "correct_answer": "B",
        "explanation": "A mean sac diameter >25 mm without an embryo (anembryonic pregnancy/blighted ovum) is diagnostic of pregnancy failure per SMFM/ACOG criteria. Smaller sacs may be indeterminate and require follow-up.",
        "image_url": "",
    },
    {
        "key": "q31", "order": 31, "section_heading": "",
        "label": "CRL cutoff for failed pregnancy",
        "question_text": "The CRL cutoff above which absence of cardiac activity is diagnostic of failed pregnancy is:",
        "choice_a": ">5 mm",
        "choice_b": ">6 mm",
        "choice_c": ">7 mm",
        "choice_d": ">10 mm",
        "correct_answer": "C",
        "explanation": "Per ACOG/SMFM guidelines, absence of cardiac activity with CRL ≥7 mm is diagnostic of embryonic demise. CRL <7 mm without cardiac activity may be indeterminate — follow-up scan in 7–10 days is recommended.",
        "image_url": "",
    },
    # Blighted Ovum
    {
        "key": "q32", "order": 32, "section_heading": "Blighted Ovum",
        "label": "Blighted ovum definition",
        "question_text": "A blighted ovum is best described as:",
        "choice_a": "An ectopic pregnancy",
        "choice_b": "Failed implantation",
        "choice_c": "An anembryonic pregnancy (fertilized egg that fails to develop an embryo)",
        "choice_d": "A twin pregnancy",
        "correct_answer": "C",
        "explanation": "A blighted ovum (anembryonic pregnancy) occurs when a fertilized egg implants in the uterus but fails to develop an embryo. The gestational sac grows but remains empty. It is the most common cause of first trimester miscarriage.",
        "image_url": "",
    },
    {
        "key": "q33", "order": 33, "section_heading": "",
        "label": "Blighted ovum diagnostic feature",
        "question_text": "Which finding is diagnostic of a blighted ovum?",
        "choice_a": "CRL >7 mm",
        "choice_b": "Mean sac diameter >25 mm with no yolk sac or embryo",
        "choice_c": "FHR <100 bpm",
        "choice_d": "Free fluid in pelvis",
        "correct_answer": "B",
        "explanation": "A mean sac diameter >25 mm without a yolk sac or embryo is diagnostic of anembryonic pregnancy (blighted ovum). This threshold is used to avoid false-positive diagnosis of pregnancy failure.",
        "image_url": "",
    },
    # Molar Pregnancy
    {
        "key": "q34", "order": 34, "section_heading": "Molar Pregnancy",
        "label": "Molar pregnancy ultrasound finding",
        "question_text": "The classic ultrasound finding in molar pregnancy is:",
        "choice_a": "Single intact gestational sac",
        "choice_b": "Multicystic 'snowstorm' appearance of the uterus",
        "choice_c": "Empty uterus",
        "choice_d": "Thick homogeneous placenta",
        "correct_answer": "B",
        "explanation": "Complete molar pregnancy classically appears as a 'snowstorm' — a diffusely heterogeneous, multicystic mass filling the uterus with no identifiable fetus. This is due to hydropic degeneration of chorionic villi.",
        "image_url": "",
    },
    {
        "key": "q35", "order": 35, "section_heading": "",
        "label": "Molar pregnancy mimics",
        "question_text": "Molar pregnancy is most often mistaken for:",
        "choice_a": "Ectopic pregnancy",
        "choice_b": "Retained products of conception",
        "choice_c": "Twin pregnancy",
        "choice_d": "Miscarriage in progress",
        "correct_answer": "B",
        "explanation": "Molar pregnancy can be mistaken for retained products of conception (RPOC) due to the heterogeneous intrauterine content. β-hCG is characteristically very elevated in molar pregnancy, which helps differentiate it.",
        "image_url": "",
    },
    # Pitfalls
    {
        "key": "q36", "order": 36, "section_heading": "Pitfalls",
        "label": "β-hCG and ectopic",
        "question_text": "Which of the following is TRUE about β-hCG in relation to ectopic pregnancy?",
        "choice_a": "A negative β-hCG rules out ectopic pregnancy",
        "choice_b": "β-hCG is always reliable for dating pregnancy",
        "choice_c": "Any β-hCG level can be associated with an ectopic pregnancy",
        "choice_d": "β-hCG is only useful above 3000 IU/L",
        "correct_answer": "C",
        "explanation": "Ectopic pregnancy can occur at any β-hCG level, including very low levels. The discriminatory zone is a threshold for expected IUP visibility — not a threshold below which ectopic is excluded. Clinical context always takes precedence.",
        "image_url": "",
    },
    {
        "key": "q37", "order": 37, "section_heading": "",
        "label": "TA ultrasound limitation",
        "question_text": "A key limitation of transabdominal (TA) ultrasound in first trimester is:",
        "choice_a": "Cannot visualize the uterus",
        "choice_b": "Poor sensitivity before 8 weeks / at lower β-hCG levels",
        "choice_c": "Cannot detect ectopic pregnancy",
        "choice_d": "No role in first trimester pregnancy",
        "correct_answer": "B",
        "explanation": "TA ultrasound has lower sensitivity in early pregnancy (before 8 weeks) and at lower β-hCG levels. Transvaginal ultrasound provides better resolution and earlier detection. TA is still useful but its limitations must be recognized.",
        "image_url": "",
    },
    {
        "key": "q38", "order": 38, "section_heading": "",
        "label": "Peak ectopic rupture timing",
        "question_text": "Peak incidence of ectopic pregnancy rupture occurs at approximately:",
        "choice_a": "4 weeks",
        "choice_b": "5 weeks",
        "choice_c": "6 weeks",
        "choice_d": "~7 weeks",
        "correct_answer": "D",
        "explanation": "Ectopic pregnancy most commonly ruptures around 7 weeks gestation, though rupture can occur earlier or later. This underscores the importance of early diagnosis before rupture occurs.",
        "image_url": "",
    },
    # Clinical Integration
    {
        "key": "q39", "order": 39, "section_heading": "Clinical Integration",
        "label": "Fetal loss with cardiac activity",
        "question_text": "After cardiac activity is detected in the first trimester, the likelihood of subsequent fetal loss is approximately:",
        "choice_a": "1%",
        "choice_b": "5%",
        "choice_c": "10%",
        "choice_d": "20%",
        "correct_answer": "B",
        "explanation": "Once cardiac activity is detected in the first trimester, the miscarriage rate drops to approximately 5% in the general population. This is reassuring information to share with patients.",
        "image_url": "",
    },
    {
        "key": "q40", "order": 40, "section_heading": "",
        "label": "Empty uterus + bleeding/cramping",
        "question_text": "A patient at 8 weeks by LMP presents with bleeding and cramping. POCUS shows an empty uterus. The most likely diagnosis is:",
        "choice_a": "Normal early pregnancy",
        "choice_b": "Likely miscarriage (complete or incomplete)",
        "choice_c": "Molar pregnancy",
        "choice_d": "Ectopic pregnancy",
        "correct_answer": "B",
        "explanation": "At 8 weeks, an IUP should be clearly visible on POCUS. An empty uterus with bleeding and cramping most likely represents a complete miscarriage. However, ectopic must always be considered and excluded, particularly if β-hCG is still elevated.",
        "image_url": "",
    },
]


def seed(apps, schema_editor):
    QuizQuestion = apps.get_model("logbook", "QuizQuestion")
    for q in QUESTIONS:
        if not QuizQuestion.objects.filter(quiz_id=6, key=q["key"]).exists():
            QuizQuestion.objects.create(quiz_id=6, **q)


def unseed(apps, schema_editor):
    QuizQuestion = apps.get_model("logbook", "QuizQuestion")
    QuizQuestion.objects.filter(quiz_id=6).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0016_seed_ocular_quiz_questions"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
